# Main Colors
unrecognized_file: lightgray
recognized_file:   white
executable_file:   green
dir:               blue

# Link
dead_link: red
link:      blue

# # special files
socket:    green
blockdev:  green
chardev:   green

# Access Modes
write:     yellow
read:      gray
exec:      red
no_access: dimgray

# Age
day_old:     lightgray
hour_old:    white
no_modifier: darkgray

# File Size
file_large:  white
file_medium: lightgray
file_small:  darkgray

# Random
report: white
user:   cyan
tree:   dimgray
empty:  yellow
error:  red
normal: darkgray

# Git
addition:     green
modification: yellow
deletion:     red
untracked:    darkgray
unchanged:    white
