#!/bin/bash

# General
alias mkdir='mkdir -p'
alias l='LC_ALL=en_US.UTF-8 LANG=en ls++'
alias ll='LC_ALL=en_US.UTF-8 LANG=en ls++ -a'
alias top='top -o cpu'
alias a2rs='sudo apachectl restart'
alias tmux='TERM=xterm-256color tmux'
alias pw='pws'
alias gpgme='gpg -e -u "matt@hiddenloop.com" -r "matt@hiddenloop.com"'
alias rerunfix='sed '/^$/d' ./rerun.txt > ~/Desktop/rerun.txt'
alias mydropbox='HOME=$HOME/My\ Dropbox /Applications/Dropbox.app/Contents/MacOS/Dropbox'

# https://github.com/trapd00r/ls--/issues/14
alias ll=' LC_ALL=en_US.UTF-8 LANG=en ls++ -a'

# Synergy http://synergy-foss.org/
alias syns_start='synergys -f --config ~/.synergy'
alias syns_connect='synergyc -f Hoth.local'

# Quick project cds
alias cdpmf='cd /u/apps/faqtory'
alias cdpms='cd /u/apps/pmfaqtory-store'
alias cdbe='cd /u/apps/beyondendurance'
alias cdhbb='cd /u/apps/bugle'
alias cdcc='cd /u/code/catapult'
alias cdht='cd /u/apps/housetrip'
alias cdts='cd /u/apps/ticketsolve'

# vnc
alias hoth='open vnc://hoth.myvnc.com'
alias alderann='open vnc://alderann.myvnc.com'

# Textmate
alias et='mate . &'
alias ett='mate stories themes app config lib db public script spec test vendor/plugins features README.* Gemfile &'

# Ticketsolve
alias sse='mongrel_rails start -e functional -p 3333'
alias ssj='java -jar vendor/seleniumrc/selenium_server/selenium-server-standalone-2.0.0.jar -port 4444'

# HouseTrip
alias sshec2ht='ssh -i ~/.ssh/matt-housetrip-aws.pem'

# Rails
alias gofast='ruby -i -pe "gsub /cache_classes \= (.+)$/, \"cache_classes = true\"" config/environments/development.rb'
alias goslow='ruby -i -pe "gsub /cache_classes \= (.+)$/, \"cache_classes = false\"" config/environments/development.rb'
alias tdl='tail -f ./log/development.log'
alias ttl='tail -f ./log/test.log'

sc () {
  if [ -f ./script/rails ]; then
    bundle exec rails c $@
  else
    ./script/console $@
  fi
}

sg () {
  if [ -f ./script/rails ]; then
    bundle exec rails g $@
  else
    ./script/generate $@
  fi
}

ss () {
  if [ -f ./Procfile ]; then
    bundle exec foreman start $@
  elif [ -f ./script/rails ]; then
    bundle exec rails s $@
  else
    ./script/server $@
  fi
}

sspe () {
  if [ -f ./Procfile ]; then
    sudo bundle exec rails server thin -p 80 $@
  elif [ -f ./script/rails ]; then
    sudo bundle exec rails s -p80 $@
  else
    sudo ./script/server -p80 $@
  fi
}

# Bundler / Rake / Spec / Cucumber
alias be='bundle exec'
alias ber='bundle exec rake'
alias bes='bundle exec spec'
alias bec='bundle exec cucumber'
alias fb='bundle exec rake flex:build:ant[compile]'
alias rdbm='bundle exec rake db:migrate'
alias rdbp='bundle exec rake db:test:prepare'
alias rsp='bundle exec rake spec'

# Ruby
alias rbenvit='rbenv shell `cat .rbenv-version`'

# svn
alias scm="svn commit --username matt "
alias saa="svn status | grep "^\?" | sed -e 's/? *//' | sed -e 's/ /\ /g' | xargs svn add"
alias sdm="svn status | grep "^\!" | sed -e 's/! *//' | sed -e 's/ /\ /g' | xargs svn delete"
alias srr="find . -name .svn -print0 | xargs -0 rm -rf"
alias signore='svn propedit svn:ignore'

# git
alias grr="git ls-files --deleted | xargs git rm"
alias gaa="git add ."
alias gb="git branch"
alias gd="git diff | vi -"
alias gl="git pull"
alias gp="git push"
alias gst="git status"

# mysql
alias myrestart='mysql.server restart'
alias mysql='mysql -uroot'
alias mybug='mysql bugle_development'
alias mybe='mysql beyondendurance_development'
alias mypmf='mysql faqtory_development'
alias mytsd='mysql ticketsolve_development'
alias myhtd='mysql housetrip_development'
alias myhtt='mysql housetrip_test'
