#!/bin/bash

# general
alias g='git'
alias v='vim'
alias mkdir='mkdir -p'
alias top='top -o cpu'
alias gpgme='gpg -e -u "matt@hiddenloop.com" -r "matt@hiddenloop.com"'
alias colors='for code in $(seq -w 0 255); do for attr in 0 1; do printf "%s-%03s %bTest%b\n" "${attr}" "${code}" "\e[${attr};38;05;${code}m" "\e[m"; done; done | column -c $((COLUMNS*2))'
alias irc='ssh grantham -t "screen -x"'

# https://github.com/trapd00r/ls--/issues/14
alias l='LC_ALL=en_US.UTF-8 LANG=en ls++'
alias ll=' LC_ALL=en_US.UTF-8 LANG=en ls++ -a'

# synergy http://synergy-foss.org/
alias syns_start='synergys -f --config ~/.synergy'
alias syns_connect='synergyc -f Hoth.local'

# quick project cds
alias cdpmf='cd /u/apps/faqtory'
alias cdpms='cd /u/apps/pmfaqtory-store'
alias cdbe='cd /u/apps/beyondendurance'
alias cdhbb='cd /u/apps/bugle'
alias cdcc='cd /u/code/catapult'
alias cdht='cd /u/apps/housetrip'
alias cdhtt='cd /u/apps/housetrip-parallel-test'
alias cdwb='cd /u/code/workbench'

# HouseTrip
alias spush='be rake smartling:push'
alias spull='be rake smartling:pull'
alias htps='be rake parallel:fast_prepare;be rake parallel:spec[4]'
alias htpf='be rake parallel:fast_prepare;be rake parallel:safe_features[4]'
alias boost='script/plugin install git://github.com/thedarkone/rails-dev-boost -r rails-2-3'
alias unboost='rm -r /u/apps/housetrip/vendor/plugins/rails-dev-boost'

# rails
alias gofast='ruby -i -pe "gsub /cache_classes \= (.+)$/, \"cache_classes = true\"" config/environments/development.rb'
alias goslow='ruby -i -pe "gsub /cache_classes \= (.+)$/, \"cache_classes = false\"" config/environments/development.rb'
alias tdl='tail -f ./log/development.log'
alias ttl='tail -f ./log/test.log'
alias rst='touch ./tmp/restart.txt'
alias migrations?='git diff --cached origin/production db/migrate | grep +++'
alias rbenvit='rbenv shell `cat .rbenv-version`'

sc () {
  if [ -f ./bin/rails ]; then
    ./bin/rails console $@
  elif [ -f ./script/rails ]; then
    bundle exec rails c $@
  else
    ./script/console $@
  fi
}

sg () {
  if [ -f ./bin/rails ]; then
    ./bin/rails generate $@
  elif [ -f ./script/rails ]; then
    bundle exec rails g $@
  else
    ./script/generate $@
  fi
}

ss () {
  if [ -f ./bin/rails ]; then
    ./bin/rails server $@
  elif [ -f ./script/rails ]; then
    bundle exec rails s $@
  elif [ -f ./Procfile ]; then
    bundle exec foreman start $@
  else
    ./script/server $@
  fi
}

# bundler / rake / spec / cucumber
alias be='bundle exec'
alias ber='bundle exec rake'
alias bes='bundle exec spec'
alias bec='bundle exec cucumber'
alias rdbm='bundle exec rake db:migrate'
alias rdbp='bundle exec rake db:test:prepare'
alias rsp='bundle exec rake spec'

# svn
alias scm="svn commit --username matt "
alias saa="svn status | grep "^\?" | sed -e 's/? *//' | sed -e 's/ /\ /g' | xargs svn add"
alias srr="find . -name .svn -print0 | xargs -0 rm -rf"

# git
alias grr="git ls-files --deleted | xargs git rm"
alias gaa="git add ."
alias gb="git list-branches"
alias gd="git diff | vi -"
alias gl="git pull"
alias glg="git lg"
alias gp="git push"
alias gst="git st"

# mysql
alias myrestart='mysql.server restart'
alias mysql='mysql -uroot'
alias mybug='mysql bugle_development'
alias mybe='mysql beyondendurance_development'
alias mypmf='mysql faqtory_development'
alias myhtd='mysql housetrip_development'
alias myhtp='mysql housetrip_production_like'
alias myhtt='mysql housetrip_test'
