#!/bin/bash

# general
alias g='git'
alias v='vim'
alias vi='vim'
alias gpgme='gpg -e -u "matt@hiddenloop.com" -r "matt@hiddenloop.com"'
alias irc='ssh kessel -t "screen -x"'
alias con='tail -40 -f /var/log/system.log'
alias gpg='gpg2'
alias notes="vi ~/Documents/system/notes"
alias todos="vi ~/Documents/system/todos"
alias secrets="vi ~/Documents/system/secrets"

# https://github.com/trapd00r/ls--/issues/14
alias ll=' LC_ALL=en_US.UTF-8 LANG=en ls++ -a'

# quick project cds
alias cdpmf='cd /u/apps/faqtory'
alias cdpms='cd /u/apps/pmfaqtory-store'
alias cdbe='cd /u/apps/beyondendurance'
alias cdhbb='cd /u/apps/bugle'
alias cdwb='cd /u/code/workbench'

# roo
alias cdr='cd /u/apps/orderweb'
alias test_refresh='rm tmp/db/test*;RAILS_ENV=test bundle exec rake db:refresh'

# git commit extracting story ID from branch name
function gc {
  if [ -n "$1" ]
  then
    STORY_ID=$story_id_from_git_branch
    # does story id already exist in arg?
    if [[ $1 =~ "[$STORY_ID]" ]]; then
      GIT_COMMIT_MSG=$1
    else
      # prefix message with [story-id]
      GIT_COMMIT_MSG="[$STORY_ID] $1"
    fi;

    git commit -am "$GIT_COMMIT_MSG"
  else
    echo "usage: gc 'your commit message'"
  fi
}

# rails / ruby
alias gofast='ruby -i -pe "gsub /cache_classes \= (.+)$/, \"cache_classes = true\"" config/environments/development.rb'
alias goslow='ruby -i -pe "gsub /cache_classes \= (.+)$/, \"cache_classes = false\"" config/environments/development.rb'
alias tdl='tail -f ./log/development.log'
alias ttl='tail -f ./log/test.log'
alias rst='touch ./tmp/restart.txt'
alias rbenvit='rbenv shell `cat .ruby-version`'

# bundler / rake / spec / cucumber
alias be='bundle exec'
alias ss='bundle exec rails server'
alias sc='bundle exec rails console'
alias sg='bundle exec rails generate'
alias bes='bundle exec rspec'
alias bec='bundle exec cucumber'
alias rdbm='bundle exec rake db:migrate'
alias rdbp='bundle exec rake db:test:prepare'

# git
alias gb="git branch"
alias gg="git pull"
alias gp="git push"
alias grm="git rebase master -i"

# mysql
alias mysql='mysql -uroot'
alias mypmf='mysql faqtory_development'
