#!/usr/bin/env bash
set -e

################################################################################
# find_up_ - https://github.com/direnv/direnv/wiki/Find-Up-with-Alternates
#          - e.g. `find_up_ .node-version .nvmrc`
################################################################################

find_up_()
{
  (
    while true; do
      for v in "${@}"; do
        if [[ -f "${v}" ]]; then
          echo "${PWD}/${v}"
          return 0
        fi
      done

      if [[ "${PWD}" == / ]] || [[ "${PWD}" == // ]]; then
        return 1
      fi

      cd ..
    done
  )
}
