#!/usr/bin/env bash
set -e

################################################################################
# common .envrc - see ~/.config/direnv/direnvrc and `man direnv-stdlib`
################################################################################

# ruby
use chruby --auto

# add utils to PATH
PATH_add ~/bin

# aws-vault should use login keychain
export AWS_VAULT_KEYCHAIN_NAME=login
