#!/usr/bin/env bash
set -e

################################################################################
# Common .envrc - see ~/.direnvrc and `man direnv-stdlib`
################################################################################

# auto-switch rubies
use chruby --auto

# add ~/bin folder to PATH
PATH_add ~/bin
# add cargo to PATH
PATH_add ~/.cargo/bin

# switch nodes, with `use node` and a local ~/.nvmrc or ~/.node-version
export NODE_VERSIONS=~/.node-versions
