#!/usr/bin/env bash
set -e

################################################################################
# Common .envrc - see ~/.direnvrc and `man direnv-stdlib`
################################################################################

# auto-switch rubies
use chruby --auto

# add ~/bin folder to PATH
PATH_add ~/bin
