#!/bin/bash

# https://github.com/junegunn/fzf
# brew install fzf
# /usr/local/opt/fzf/install

# style the bash fzf
export FZF_DEFAULT_OPTS='--height 40% --reverse'

# helper to echo and execute a command
function _echo_and_execute() {
  echo $1
  eval $1
}

## History related

# search history and re-run, filtering first with grep on arg, then with fzf; e.g
# USAGE: hist [keyword for grep]
function hist(){
  $(history | tail -r | grep -iE "$*" | fzf | xargs | cut -d ' ' -f 2- | xargs | tr -d '\n' | pbcopy)
}


## PID related

# helper to fzf a PID
function _fzf_pid() {
  echo -n $(ps axww -o pid,user,%cpu,%mem,start,time,command | fzf | sed 's/^ *//' | cut -f1 -d' ')
}

# copy a PID to clipboard
# USAGE: psp
function psp() {
  pid=$(_fzf_pid)
  echo -n "$pid" | pbcopy
}


## GIT related

# helper to fzf a local branch, trims leading whitespace, and "*"
function _fzf_git_branch(){
  echo $(git branch | sed 's/^\*//' | fzf | xargs echo)
}

# choose branch and pass it to `command`, or copy the branch name if no args
# USAGE: gbp [command]
function gbp() {
  branch=$(_fzf_git_branch)
  if [ $# -eq 0 ]; then
    echo -n $branch | pbcopy; return;
  fi
  _echo_and_execute "$* $branch"
}

# `git branch checkout`
alias gbc="gbp git co"

# `git branch merge`
alias gbm="gbp git merge"

# `git branch delete
alias gbd="gbp git br -D"
