#!/usr/bin/ruby

# show queries
if defined? ActiveRecord
  ActiveRecord::Base.logger = Logger.new STDOUT
  ActiveRecord::Base.clear_reloadable_connections!
end

# show requests, e.g. use app.get '/'
if defined? ActionController
  ActionController::Base.logger = Logger.new STDOUT
end

# run query
def sql(query)
  ActiveRecord::Base.connection.select_all(query)
end

# get a specific route via index or name
def route(index_or_name)
  case index_or_name
    when Integer
      Rails.application.routes.routes[index_or_name]
    when Symbol # named route
      Rails.application.routes.named_routes.get index_or_name
    end
end

# show Rails app name and RAILS_ENV name in prompt
app_env  = (ENV['RAILS_ENV'] || Rails.env)[0...3]
app_name = (defined?(Rails) ? Rails.application.class.parent_name : Dir.pwd.split('/').last).downcase
prompt   = "#{ app_name }(#{ app_env })"

# build irb prompt
IRB.conf[:PROMPT] ||= {}
IRB.conf[:PROMPT][:RAILS] = {
  :PROMPT_I    => "#{ prompt }> ",
  :PROMPT_N    => "#{ prompt }| ",
  :PROMPT_C    => "#{ prompt }| ",
  :PROMPT_S    => "#{ prompt }%l ",
  :RETURN      => "=> %s\n",
  :AUTO_INDENT => true,
}
IRB.conf[:PROMPT_MODE] = :RAILS

if defined?(Freeagent)
  def company
    @_company ||= Company.find_by_subdomain('fac')
  end

  def user
    @_user ||= company.account_owner
  end
end
