#!/usr/bin/ruby

# load Rails (unless it has been already, needed for Rails 2 apps)
unless defined?(Rails)
  require File.join(Dir.getwd, 'config', 'environment.rb')
end

# show queries
ActiveRecord::Base.logger = Logger.new STDOUT
ActiveRecord::Base.clear_reloadable_connections!

# show requests
ActionController::Base.logger = Logger.new STDOUT

# run query
def sql(query)
  ActiveRecord::Base.connection.select_all(query)
end

# allow path/route helper methods
if defined?(Rails.application)
  include Rails.application.routes.url_helpers
end


# hirb view for routes
if defined?(ActionDispatch)
  class Hirb::Helpers::Route < Hirb::Helpers::AutoTable
    def self.render(output, options = {})
      super( output.requirements.map{ |k,v|
        [k, v.inspect]
        }, options.merge({
          :headers     => [output.name || '', "#{ output.verb || 'ANY' } #{ output.path }"],
          :unicode     => true,
          :description => nil,
          }) )
    end
  end

  Hirb.add_view ActionDispatch::Routing::RouteSet, :class => Hirb::Helpers::Route
end

if defined?(Rails.application)

  # print a short (and long) route list
  def routes(long_output = false)
    if long_output
      Rails.application.routes.routes.each{ |e| puts Hirb::Helpers::Route.render(e)  }
      true
    else
      Hirb::Console.render_output Rails.application.routes.routes.map{|e|
        [e.name || '', e.verb || 'ANY', e.path]
      },{
        :class   => Hirb::Helpers::AutoTable,
        :headers => %w<name verb path>,
      }
    end
  end
end

# show Rails App name and RAILS_ENV name in prompt
app_env  = Rails.env[0...3]
app_name = (defined?(Rails.application) ? Rails.application.class.parent_name : Dir.pwd.split('/').last).downcase
prompt   = "#{ app_name }(#{ app_env })"
IRB.conf[:PROMPT] ||= {}
IRB.conf[:PROMPT][:RAILS] = {
  :PROMPT_I    => "#{ prompt }> ",
  :PROMPT_N    => "#{ prompt }| ",
  :PROMPT_C    => "#{ prompt }| ",
  :PROMPT_S    => "#{ prompt }%l ",
  :RETURN      => "=> %s\n",
  :AUTO_INDENT => true,
}
IRB.conf[:PROMPT_MODE] = :RAILS
