#!/bin/bash

# https://github.com/garybernhardt/selecta
# brew install selecta

# helper to print and execute command string
function _selecta_echo_and_execute() {
  echo $1
  eval $1
}

# helper to selecta PID
function _selecta_pid() {
  echo -n $(ps axww -o pid,user,%cpu,%mem,start,time,command | selecta | sed 's/^ *//' | cut -f1 -d' ')
}

# search history and copy, filtering first with grep, then with selecta; e.g
# USAGE: hist [keyword for grep]
function hist(){
  $(history | tail -r | grep -iE "$*" | selecta | xargs | cut -d ' ' -f 2- | xargs | tr -d '\n' | pbcopy)
}



# PID related

# copy PID
function psc() {
  pid=$(_selecta_pid)
  echo -n "$pid" | pbcopy
}

# kill PID (with an optional signal)
function psk() {
  pid=$(_selecta_pid)
  kill $* $pid
}



# git related

# helper to select a local branch, trims leading whitespace, and "*"
function _selecta_git_branch(){
  echo $(git branch | sed 's/^\*//' | selecta | xargs echo)
}

# `git branch select``
# selecta branch and pass it to `command`, or copy the branch name if no args
# USAGE: gbs [command]
function gbs() {
  branch=$(_selecta_git_branch)
  if [ $# -eq 0 ]; then
    echo -n $branch | pbcopy; return;
  fi
  _selecta_echo_and_execute "$* $branch"
}

# alias to `git branch pick` acronym
alias gbp='gbs'

# `git branch checkout`
alias gbc="gbs git co"

# `git branch delete
alias gbd="gbs git br -D"
