#!/usr/bin/env bash
HEART_CONNECTED=☀
HEART_DISCONNECTED=☼

case $(uname -s) in
    "Darwin")
        ioreg -c AppleSmartBattery -w0 | \
        grep -o '"[^"]*" = [^ ]*' | \
        sed -e 's/= //g' -e 's/"//g' | \
        sort | \
        while read key value; do
            case $key in
                "MaxCapacity")
                    export maxcap=$value;;
                "CurrentCapacity")
                    export curcap=$value;;
                "ExternalConnected")
                    export extconnect=$value;;
            esac
            if [[ -n $maxcap && -n $curcap && -n $extconnect ]]; then
                if [[ "$curcap" == "$maxcap" ]]; then
                    exit
                fi
                if [[ "$extconnect" == "Yes" ]]; then
                    echo "#[bg=colour000,fg=colour071]⮂#[bg=colour071,fg=colour235]" $HEART_CONNECTED $(( 100 * $curcap / $maxcap ))"% #[bg=colour071]"
                else
                    echo "#[bg=colour000,fg=colour235]⮂#[bg=colour235,fg=colour245]" $HEART_DISCONNECTED $(( 100 * $curcap / $maxcap ))"% #[bg=colour235]"
                fi
                break
            fi
        done
esac
