#!/usr/bin/env bash
set -e

function build {
  local segments=(
    "lan_ip" \
    "battery" \
    "disk" \
    "memory" \
    "cpu_temp" \
    "cpu" \
    "env_info" \
  )

  local dividers=(
    "#[fg=colour213,bg=colour000]" \
    "" \
    " " \
    "  " \
    "  " \
    "  " \
  )

  local output=""
  for i in "${!segments[@]}"; do
    output="$(~/.tmux/segments/${segments[$i]})${dividers[$i]}$output"
  done

  echo $output
}

build
