#!/usr/bin/env bash

set -e

function cpu_load {
  local cpu_load=$(
    top -l 1 | \
      head -n 4 | \
      tail -n 1 | \
      awk '{printf "%3d%%\n", $3}' | \
      sed 's/( *|%)//'
  )

  # defaults
  local line_icon=" "
  local line_length=10
  local base_color=133
  local active_count=$(($cpu_load / $line_length))

  # build load line
  # local active_count=3
  local load_line=""

  for (( i = 0; i < line_length; i++ )); do
    local line_color="#[fg=colour$(($base_color - $i))]"

    if [[ $i -ge $active_count ]]; then
      line_icon=" "
    elif [[ $active_count -gt 2 ]]; then
      line_icon="✺"
    else
      line_icon="☉"
    fi

    load_line="$load_line$line_color$line_icon"
  done

  echo "$load_line#[default]"
}

echo $(cpu_load)
