#!/usr/bin/env bash
set -e

function lan_ip {
  local nic0="en0"
  local nic1="en1"

  # get wired IP
  local lan_ip=$(
    /sbin/ifconfig $nic0 2>/dev/null | \
      grep 'inet ' \
      | awk '{print $2}'
  )

  # or get wireless IP
  if [ -z "$lan_ip" ]; then
    lan_ip=$(
      /sbin/ifconfig $nic1 2>/dev/null | \
        grep 'inet ' | \
        awk '{print $2}'
    )
  fi

  if [ -n "$lan_ip" ]; then
    echo "#[bg=colour016,fg=colour236]#[bg=colour236,fg=colour007] ${lan_ip} #[bg=colour236,fg=colour016]#[default]"
  fi
}

lan_ip
