#!/usr/bin/env bash

set -e

function cpu_load {
  local cpu_load=$(
    top -l 1 | \
      head -n 4 | \
      tail -n 1 | \
      awk '{printf "%3d%%\n", $3}' | \
      sed 's/ //'
  )

  # defaults
  local line_icon="☉"
  local line_length=10
  local base_color=131

  # build load line
  local cpu=${cpu_load%\%*}
  local active_count=$(($cpu / $line_length))
  local load_line=""

  for (( i = 0; i < $line_length; i++ )); do
    if [[ $active_count > 2 ]]; then
      local line_color="#[fg=colour$(($base_color - $i))]"
      line_icon="✺"
    fi

    if [[ $i < $active_count ]]; then
      load_line="$load_line$line_color$line_icon"
    fi
  done

  if [[ $active_count > 0 ]]; then
    echo "$load_line#[default]  "
  fi
}

function free_memory {
  local pages_free=$(
    vm_stat | \
      grep free | \
      awk '{ print $3 }' | \
      sed 's/\.//'
  )

  echo "$((($pages_free * 4096)/1048576)) Mb"
}

function hd_percentage_free {
  local percent=$((100-(`df | head -n 2 | tail -n 1 | awk '{printf "%d", $5}'`)))

  # color range
  local color_lower_than=40
  local fg_colors=(161 167 173 179 250)
  local range=$(($percent / ($color_lower_than / ${#fg_colors[*]})))
  local fg_color=default

  # only color if less than this
  if (( $percent < $color_lower_than )); then
    fg_color=${fg_colors[$range]}
  fi

  echo "#[fg=colour$fg_color]HD $percent%#[default]"
}

function machine_status {
  echo "$(cpu_load)$(free_memory)  $(hd_percentage_free)"
}

machine_status
