#!/usr/bin/env bash
set -e

function unused_memory {
  local installed_memory=$(sysctl -n hw.memsize)
  local installed_memory_in_gb=$(bc <<< "scale=2; $installed_memory/1024/1024/1000")
  local page_types=("wired down" "active" "inactive")
  local all_consumed=0

  for page_type in "${page_types[@]}"; do
    local consumed=$(vm_stat | grep "Pages ${page_type}:" | awk -F: '{print $2}' | tr -d '[[:space:]]' | grep -e "[[:digit:]]*" -ho)
    local consumed_gb=$(bc <<< "scale=2; ($consumed*4096)/1024/1024/1000")
    all_consumed=$(bc <<< "scale=2; $all_consumed+$consumed_gb")
  done

  printf "%.2fGB" $(bc <<< "scale=2; $installed_memory_in_gb-$all_consumed")
}

unused_memory
