#!/usr/bin/env zsh

################################################################################
# Misc
################################################################################

alias irc='ssh chunnel.wan -t "screen -x"'
alias ircl='ssh chunnel -t "screen -x"'
alias plan='FINDDATES=$(date "+%b\ %d\|")$(date -v "-1d" "+%b\ %d\|")$(date "+%b"); vi +/$FINDDATES /Users/matt/Obsidian\ Vault/Plan/$(date "+%Y").md'
alias reload='source ~/.zshrc'
alias vnc-hoth='ssh -f hoth.vnc.tunnel -N; open vnc://localhost:5999'
alias tml='tmux ls'
alias lc='colorls' # https://github.com/athityakumar/colorls
alias ll='colorls -lA --sd --gs -t' # 1 per line, newest & dirs first, git info

alias tree='colorls --tree' # tree with dirs first
alias wget='wget --no-hsts' # stop logging .hsts files
alias help='tldr'  # http://tldr.sh

alias stfu="osascript -e 'set volume output muted true'"
alias flushdns="dscacheutil -flushcache"

alias f='vi $(fzf --preview="cat {}")'

################################################################################
# Shopify
################################################################################

alias shoppy='ssh shopify -t $(brew --prefix)/bin/tmux attach-session'
alias vscode='spin code shopify shopify--storefront-renderer; spin code shopify shopify--shopify/areas/core/shopify'

################################################################################
# Overrides
################################################################################

alias cat='bat --theme=TwoDark' # https://github.com/sharkdp/bat
alias ping='prettyping'         # https://github.com/denilsonsa/prettyping
alias top='btop'                # https://github.com/aristocratos/btop

# always enable colored `grep` output`

alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"

################################################################################
# Quick cds
################################################################################

alias cdwb='cd ~/code/workbench'

################################################################################
# Ruby / Rails
################################################################################

alias be='bundle exec'
alias r="rails"
alias ss='rails server'
alias sc='rails console'
alias sg='rails generate'
alias rdbp='rails db:prepare'
alias rdbtp='rails db:prepare RAILS_ENV=test'
alias rdbmt='rails db:migrate RAILS_ENV=test'
alias tdl='tail -f ./log/development.log'
alias tdlp="tdl | egrep 'Completed|Processing|Parameters\:'"
alias tdlnc="tdl | egrep -v -e '^.*(\[ActionCable\]|\[Action Cable\]|\[Socket\]|\[ActiveJob\]|\[Active Job\]).*$'"
alias rst='touch ./tmp/restart.txt'
alias sshot='open ./tmp/screenshots'

# reschema your rails app, recreate db and load schema (no seeding)
alias rscheme='rails db:drop;rails db:create;rails db:schema:load'

# run tests for all tests files that have changed in this branch (from master)
# filters out deleted tests
alias rtc='rails test $(git diff --diff-filter=d --name-only master test | grep "_test.rb" | tr "\n" " ")'
alias rstc='rspec $(git diff --diff-filter=d --name-only master spec | grep "_spec.rb" | tr "\n" " ")'

################################################################################
# Git
################################################################################

alias gb='git branch --verbose'
alias gg='git pull'
alias gp='git push'
alias gpf='git push --force-with-lease'
alias gl="git log --graph --pretty=format:'%h - %d %s (%cr) <%an>' | vim -R -c 'set filetype=git nowrap' -"
alias grm='git rebase $(git_main_branch) -i'
alias gca='git amend'
alias gup='git upstream'

# GitHub CLI - https://cli.github.com
alias gpr='gh pr create'

# autocorrect fixes
alias rspec='nocorrect rspec'
alias kamal='nocorrect kamal'
