#!/usr/bin/env zsh

################################################################################
# Misc
################################################################################

alias fhp='cd ~/Documents/firehose/job\ prep/;ll;mate ~/Documents/firehose/resources/mentor_session_test.rb;open https://www.thefirehoseproject.com/courses'
alias irc='ssh kessel.lan -t "screen -x"'
alias ircr='ssh kessel -t "screen -x"'
alias scratch='vi ~/Documents/system/notes/scratch.md'
alias todos='vi ~/Documents/system/notes/todos.md'
alias secrets='vi ~/Documents/system/notes/secrets.enc.md'
alias plan='vi -c ":$" ~/Documents/system/notes/plans/'`date "+%Y"`'.md'
alias reload='source ~/.zshrc'
alias vnc-hoth='ssh -f hoth.vnc.tunnel -N; open vnc://localhost:5999'
alias tml='tmux ls'
alias lc='colorls' # https://github.com/athityakumar/colorls
alias ll='colorls -lA --sd --gs -t' # 1 per line, newest & dirs first, git info

alias tree='colorls --tree' # tree with dirs first
alias wget='wget --no-hsts' # stop logging .hsts files
alias help='tldr'  # http://tldr.sh
alias intg='devkit server list | grep -E "int[0-9]+\s+$" | head -n 1 | xargs devkit server grab'

################################################################################
# Overrides
################################################################################

alias cat='bat --theme=TwoDark' # https://github.com/sharkdp/bat
alias ping='prettyping'         # https://github.com/denilsonsa/prettyping
alias top='htop'                # http://hisham.hm/htop/

################################################################################
# Quick cds
################################################################################

alias cdf='cd ~/apps/freeagent'
alias cdwb='cd ~/code/workbench'
alias cdpmf='cd ~/apps/pmfaqtory-store'
alias cdob='cd ~/apps/open-banking-on-rails'

################################################################################
# Ruby / Rails
################################################################################

alias be='bundle exec'
alias ss='rails server'
alias sc='rails console'
alias sg='rails generate'
alias rdbp='rake db:prepare'
alias rdbtp='rake db:prepare RAILS_ENV=test'
alias rdbmt='rake db:migrate RAILS_ENV=test'
alias tdl='tail -f ./log/development.log'
alias tdlp="tdl | egrep 'Completed|Processing|Parameters\:'"
alias rst='touch ./tmp/restart.txt'

################################################################################
# Git
################################################################################

alias gb='git branch'
alias gg='git pull'
alias gp='git push'
alias gl="git log --graph --pretty=format:'%h - %d %s (%cr) <%an>' | vim -R -c 'set filetype=git nowrap' -"
alias grm='git rebase main -i'
alias grmm='git rebase master -i'
alias gca='git commit --amend --no-edit'
alias gpf='git push --force-with-lease'

# GitHub CLI - https://cli.github.com

alias gpr='gh pr create'
alias gcsi='gh issue list --label "Core Services"'

################################################################################
# Disabled corrections
################################################################################

alias rspec='nocorrect rspec'
alias spring='nocorrect spring'
alias rg='nocorrect rg'
