#!/usr/bin/env zsh

# https://github.com/postmodern/chruby#auto-switching
if [ ! -d /opt/dev/sh/chruby ]; then
  source $(brew --prefix)/share/chruby/chruby.sh
  source $(brew --prefix)/share/chruby/auto.sh
fi

if [[ $TMUX ]]; then
  # ensure hooks are enabled
  type add-zsh-hook > /dev/null 2>&1 || autoload -Uz add-zsh-hook

  function update_tmux_ruby_version_env_info {
    local pane_id=$(tmux display -p "#{pane_id}" | sed 's/^\%//' 2>&1)
    local ruby_version=$(ruby --version | cut -d' ' -f2)
    tmux setenv -g TMUX_PANE_${pane_id}_RUBY_VERSION ${ruby_version}
  }

  add-zsh-hook precmd update_tmux_ruby_version_env_info
fi


