#!/usr/bin/env zsh

################################################################################
# Editing mode with vi
################################################################################

bindkey -v          # use vi, see mappings below
export KEYTIMEOUT=1 # less lag when switching between modes
export EDITOR=vi    # vi for editing

bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^A' vi-beginning-of-line
bindkey '^E' vi-end-of-line
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward

################################################################################
# Options
################################################################################

setopt ALWAYS_TO_END      # move cursor to end after completion
setopt AUTO_CD            # cd to dir if exists and not a cmd
setopt COMPLETE_IN_WORD   # completion from both ends
setopt CORRECT            # auto guess cmds
setopt NOTIFY             # report jobs right away
setopt PROMPT_SUBST       # allow dynamic prompt substition
setopt PUSHD_IGNORE_DUPS  # ignore dup dirs on the dir stack
setopt PUSHD_TO_HOME      # psuhd on its own, pushes to $HOME
setopt EXTENDED_GLOB      # better globbing e.g. ls (bin|lib)* ls -d ^*.json ls -R ls *(U)
setopt RM_STAR_SILENT     # go ahead, rm /* if you like

################################################################################
# History
################################################################################

setopt EXTENDED_HISTORY   # more info in history file
setopt HIST_FIND_NO_DUPS  # hide dups in results
setopt HIST_IGNORE_DUPS   # dont store dups
setopt HIST_IGNORE_SPACE  # dont store cmds that start with a <space>
setopt SHARE_HISTORY

export HISTFILE="$HOME/.history"
export HISTFILESIZE=50000000
export HISTSIZE=5000000
export SAVEHIST=$HISTSIZE

autoload -U history-search-end # arrow searching with existing chars
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end

bindkey "\e[A" history-beginning-search-backward-end
bindkey "\e[B" history-beginning-search-forward-end

################################################################################
# Colours
#
# I've modifed ocean-dark from ocean, with black bg and extra colours in the 256
# space. See http://chriskempson.com/projects/base16/ for details.
################################################################################

autoload -Uz colors && colors
export CLICOLOR=1
export LSCOLORS="ExGxBxDxCxEgEdxbxgxcxd"
export GREP_OPTIONS="--color"

# source colorscheme if we have a prompt
# TODO: use a common colourscheme that works in Terminal & iTerm (incl. vim)
local colorscheme="$HOME/.zsh/base16-shell/base16-ocean-dark.sh"
[ -n "$PS1" ] && [[ -s $colorscheme ]] && source $colorscheme

################################################################################
# Completion
################################################################################

# faster compinit, don't check ~/.zcompdump every time, only once/day
autoload -Uz compinit
if [ $(date +'%j') != $(stat -f '%Sm' -t '%j' ~/.zcompdump) ]; then
  compinit
else
  compinit -C
fi

# use menu select and match approximately
zstyle ':completion:*:*:*:*:*' menu select
zstyle ':completion:*::::' _expand completer _complete _match _approximate

# case- and hyphen-insensitive completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z-_}={A-Za-z_-}' 'r:|=*' 'l:|=* r:|=*'

# pasting with tabs doesn't perform completion
zstyle ':completion:*' insert-tab pending

# complete .. and .
zstyle ':completion:*' special-dirs true

# colours with LSCOLORS
zstyle ':completion:*' list-colors ${(s.:.)LSCOLORS}

# messaging
zstyle ':completion:*' verbose yes
zstyle ':completion:*:descriptions' format "$fg[yellow]%B--- %d%b"
zstyle ':completion:*:messages' format '%d'
zstyle ':completion:*:warnings' format "$fg[red]No matches for:$reset_color %d"
zstyle ':completion:*:corrections' format '%B%d (errors: %e)%b'
zstyle ':completion:*' group-name

# split cmd options into groups
zstyle ':completion:*' tag-order \
    'options:-long:long\ options
     options:-short:short\ options
     options:-single-letter:single\ letter\ options'
zstyle ':completion:*:options-long' ignored-patterns '[-+](|-|[^-]*)'
zstyle ':completion:*:options-short' ignored-patterns '--*' '[-+]?'
zstyle ':completion:*:options-single-letter' ignored-patterns '???*'

################################################################################
# Misc
################################################################################

# easy cd to apps and code
typeset -U cdpath
cdpath=( $HOME ~/apps ~/code ~/code/lolcommits-plugins $cdpath )

# added by travis gem
[ -f /Users/matt/.travis/travis.sh ] && source /Users/matt/.travis/travis.sh
