#!/usr/bin/env zsh

########################################################################
# FreeAgent
########################################################################

# app env vars
export DB_HOST=127.0.0.1
export STATSD_HOST=localhost
export GRAPHITE_HOST=localhost
export FREEAGENT_CACHE_STORE=memcached

# aliases
alias intg='devkit server list | grep -E "int[0-9]+\s+$" | head -n 1 | xargs devkit server grab'
alias cdf='cd /u/apps/freeagent'
alias jlog='jenkins-log'

# use older QT and node@6
export PATH="/usr/local/opt/qt@5.5/bin:/usr/local/opt/node@6/bin:$PATH"
# add jenkins log to path
export PATH="/u/code/jenkins-log/bin:$PATH"

# encrypt a string with eyaml in the puppet repo and copy to clipboard
function puppet_encrypt {
  return_to_dir=$PWD
  cd /u/code/puppet-config;
  bundle exec eyaml encrypt -o string -s "$1" | tr -d '\n' | pbcopy
  cd $return_to_dir
}
