#!/usr/bin/env zsh

################################################################################
# scmpuff - https://github.com/mroth/scmpuff
################################################################################

if hash scmpuff >/dev/null 2>&1; then
  eval "$(scmpuff init -s)"
fi

################################################################################
# auto-squash with master
################################################################################

function fixup {
  CHANGES=`git status -s`
  if [ -z "$CHANGES" ]
  then
    echo "aborting .. nothing to add or commit"
  else
    REBASE_WITH="master"
    if [ -n "$1" ]
    then
      REBASE_WITH=$1
    fi

    # commit last change as a fixup with previous commit; rebasing with
    # master and auto-squashing (with no editor)
    git add .
    git commit --fixup HEAD
    GIT_SEQUENCE_EDITOR=: git rebase -i --autosquash $REBASE_WITH
  fi
}

################################################################################
# first push
################################################################################

function gfp {
  # pushes then sets upstream for a branch; git config for [push] must
  # set with: `default = current`
  git push
  git branch --set-upstream-to=origin/"$git_branch" "$git_branch"
}
