#!/usr/bin/env zsh

# TODO: consider defer for setting this
# https://github.com/romkatv/zsh-defer
# https://github.com/Mellbourn/dotfiles/blob/master/.zshrc#L59
# E.g. zsh-defer -1sm -t 0.2 -c 'printf "\033]2;$VCS_STATUS_LOCAL_BRANCH\033\\"'

function precmd_set_tmux_pane_env_info() {
  if [[ $TMUX ]]; then
    tmux setenv -g TMUX_PANE_${TMUX_PANE#%}_RUBY_VERSION ${RUBY_VERSION:-'sys'}
  fi
}
precmd_functions+=(precmd_set_tmux_pane_env_info)