#!/bin/bash

# general
alias g='git'
alias v='vim'
alias vi='vim'
alias fhp='cd ~/Documents/firehose/job\ prep/;ll;mate ~/Documents/firehose/resources/mentor_session_test.rb;open https://www.thefirehoseproject.com/courses'
alias gpgenc='gpg --encrypt --sign --armor -r' # args are email and file
alias irc='ssh kessel -t "screen -x"'
alias con='tail -40 -f /var/log/system.log'
alias gpg='gpg2'
alias scratch="vi ~/Documents/system/notes/scratch.md"
alias todos="vi ~/Documents/system/notes/todos.md"
alias secrets="vi ~/Documents/system/notes/secrets.enc.md"

# VNC (needs ssh config set)
alias vnc-hoth="ssh -f hoth.vnc.tunnel -N; open vnc://localhost:5999"
alias vnc-dagobah="ssh -f dagobah.vnc.tunnel -N; open vnc://localhost:5998"

# tmux, list or attach to a session
alias tm="tmux ls"
alias tma="tmux a -t "

# quick project cds
alias cdpmf='cd /u/apps/faqtory'
alias cdpms='cd /u/apps/pmfaqtory-store'
alias cdbe='cd /u/apps/beyondendurance'
alias cdhbb='cd /u/apps/bugle'
alias cdwb='cd /u/code/workbench'

# freeagent
alias cdf='cd /u/apps/freeagent'
alias intg='devkit server list | grep -v "\t\S" | head -n 1 | xargs devkit server grab'

# encrypt a string with eyaml for puppet config and copy to clipboard
function pupencrypt {
  working_dir=$PWD
  cd /u/code/puppet-config;
  bundle exec eyaml encrypt -o string -s "$1" | tr -d '\n' | pbcopy
  cd $working_dir
}

# commit changes as fixup to previous commit, rebase with branch (master) with
# auto-squashing (no editor)
function fixup {
  CHANGES=`git status -s`
  if [ -z "$CHANGES" ]
  then
    echo "aborting .. nothing to add or commit"
  else
    REBASE_WITH="master"
    if [ -n "$1" ]
    then
      REBASE_WITH=$1
    fi

    git add .
    git commit --fixup HEAD
    GIT_SEQUENCE_EDITOR=: git rebase -i --autosquash $REBASE_WITH
  fi
}


# git commit extracting story ID from branch name
function gc {
  if [ -n "$1" ]
  then
    STORY_ID=$story_id_from_git_branch
    # does story id already exist in arg?
    if [[ $1 =~ "[$STORY_ID]" ]]; then
      GIT_COMMIT_MSG=$1
    else
      # prefix message with [story-id]
      GIT_COMMIT_MSG="[$STORY_ID] $1"
    fi;

    git commit -S -am "$GIT_COMMIT_MSG"
  else
    echo "usage: gc 'your commit message'"
  fi
}

# first push of a branch, pushes then sets upstream for it
# requires git push setting: `default = current`
function gfp {
  git push
  git branch --set-upstream-to=origin/"$br" "$br"
}

# rails / ruby
alias gofast='ruby -i -pe "gsub /cache_classes \= (.+)$/, \"cache_classes = true\"" config/environments/development.rb'
alias goslow='ruby -i -pe "gsub /cache_classes \= (.+)$/, \"cache_classes = false\"" config/environments/development.rb'
alias tdl='tail -f ./log/development.log'
alias tdlr="tdl | egrep 'Processing|Parameters\:'"
alias ttl='tail -f ./log/test.log'
alias rst='touch ./tmp/restart.txt'
alias rbenvit='rbenv shell `cat .ruby-version`'

# bundler / rake / spec / cucumber
alias be='bundle exec'
alias ss='bundle exec rails server'
alias sc='bundle exec rails console'
alias sg='bundle exec rails generate'
alias bes='bundle exec rspec'
alias bec='bundle exec cucumber'
alias rdbp='bundle exec rake db:prepare'
alias rdbpp='bundle exec rake parallel:prepare'

# git
alias gb="git branch"
alias gg="git pull"
alias gp="git push"
alias gl="git log --graph --pretty=format:'%h - %d %s (%cr) <%an>' | vim -R -c 'set filetype=git nowrap' -"
alias grm="git rebase master -i"

# git commit again (without editing)
alias gca="git commit --amend --no-edit"
# force push with a lease
alias gpf="git push --force-with-lease"

# mysql
alias mysql='mysql -uroot'
alias mypmf='mysql faqtory_development'
