#!/bin/sh
#
# An example hook script to prepare the commit log message.  Called by "git
# commit" with the name of the file that has the commit message, followed by the
# description of the commit message's source. The hook's purpose is to edit the
# commit message file. If the hook fails with a non-zero status, the commit is
# aborted.
#
# see here for details:  https://git-scm.com/docs/githooks#_prepare_commit_msg

prepareTemplateMessage() {
  # grab template file contents (if it exists)
  template_file="$HOME/.git_commit_message_template"
  if [ -f "$template_file" ]
  then
    template_content="\n$(cat $template_file)\n"
  fi

  # prefix with story id from the current git branch if present
  if [ -n "$story_id_from_git_branch" ]
  then
    prefix="[$story_id_from_git_branch] "
  fi

  echo $prefix "short message\n$template_content$(cat $1)" > $1
}

# handle various args this script can be invoked with
case "$2,$3" in
  # Commits that already have a message
  commit,?*)
  ;;

  # Messages are one line messages e.g. from -m
  message,)
  ;;

  # when squashing commits
  squash,)
  ;;

  # Merge commits
  merge,)
    # Comments out the "Conflicts:" part of a merge commit.
    # perl -i.bak -ne 's/^/# /, s/^# #/#/ if /^Conflicts/ .. /#/; print' "$1"
  ;;

  # Non-merges with no prior messages
  *)
    prepareTemplateMessage $1
  ;;
esac

