#!/bin/sh
#
# An example hook script to prepare the commit log message.  Called by "git
# commit" with the name of the file that has the commit message, followed by the
# description of the commit message's source. The hook's purpose is to edit the
# commit message file. If the hook fails with a non-zero status, the commit is
# aborted.

# prevent this happening during rebases or when in a headless state
NAME=$(git rev-parse --abbrev-ref HEAD);
if [ "$NAME" != 'HEAD' ] ; then
  # grab template file contents (if it exists)
  template_file="$HOME/.git_commit_message_template"
  if [ -f "$template_file" ]
  then
    template_content="\n$(cat $template_file)\n"
  fi


  # prefix with story id from the current git branch if present
  if [ -n "$story_id_from_git_branch" ]
  then
    prefix="[$story_id_from_git_branch] "
  fi

  echo $prefix "short message\n$template_content$(cat $1)" > $1
fi
